import { AlertTriangle } from 'lucide-react'

export function WarningBanner() {
  return (
    <div
      className="border-b border-amber-200 bg-amber-50 px-4 py-2.5 text-center text-sm text-amber-950"
      role="status"
    >
      <p className="mx-auto flex max-w-5xl items-center justify-center gap-2">
        <AlertTriangle className="hidden h-4 w-4 shrink-0 sm:inline" aria-hidden />
        <span>
          All creatives generated by this app must be reviewed and approved by the Marketing team before
          being used in any campaign or published externally.
        </span>
      </p>
    </div>
  )
}
